export const MESSAGE_TYPES = {
    TEST: 'test',
    CHECK_MODELS_LOADING_STATE: 'checkModelsLoadingState',
    NONE_LOADED: 'allLoading',
    ALL_MODELS_LOADED: 'allModelsReady',
    ENCODER_DECODER_LOADED: 'encoderDecoderReady',
    INPAINTER_LOADED: 'inpainterReady',
    LOAD_INPAINTER: 'loadInpainter',
    DECODER_RUN: 'decoderRun',
    DECODER_RUN_RESULT: 'decoderRunResult',
    ENCODER_RUN: 'encoderRun',
    ENCODER_RUN_RESULT: 'encoderRunResult',
    INPAINTING_RUN: 'inpainterRun',
    INPAINTING_RUN_RESULT: 'inpainterRunResult',
}