export const MESSAGE_TYPES = {
    TEST: 'test',
    CHECK_MODELS_LOADING_STATE: 'checkModelsLoadingState',
    MODELS_LOADED: 'modelsReady',
    MODELS_STILL_LOADING: 'modelsNotReady',
    DECODER_READY: 'decoderReady',
    ENCODER_READY: 'encoderReady',
    INPAINTER_READY: 'inpainterReady',
    DECODER_RUN: 'decoderRun',
    DECODER_RUN_RESULT: 'decoderRunResult',
    ENCODER_RUN: 'encoderRun',
    ENCODER_RUN_RESULT: 'encoderRunResult',
    INPAINTING_RUN: 'inpainterRun',
    INPAINTING_RUN_RESULT: 'inpainterRunResult',
}