export const MESSAGE_TYPES = {
    INIT: 'init',
    CHECK_MODELS_LOADING_STATE: 'checkModelsLoadingState',
    NONE_LOADED: 'allLoading',
    ALL_MODELS_LOADED: 'allModelsReady',
    ENCODER_DECODER_LOADED: 'encoderDecoderReady',
    INPAINTER_LOADED: 'inpainterReady',
    LOAD_INPAINTER: 'loadInpainter',
    DECODER_RUN: 'decoderRun',
    DECODER_RUN_RESULT_SUCCESS: 'decoderRunResultSuccess',
    DECODER_RUN_RESULT_FAILURE: 'decoderRunResultFailure',
    ENCODER_RUN: 'encoderRun',
    ENCODER_RUN_RESULT_SUCCESS: 'encoderRunResultSuccess',
    ENCODER_RUN_RESULT_FAILURE: 'encoderRunResultFailure',
    INPAINTING_RUN: 'inpainterRun',
    INPAINTING_RUN_RESULT_SUCCESS: 'inpainterRunResultSuccess',
    INPAINTING_RUN_RESULT_FAILURE: 'inpainterRunResultFailure',
}